name: Write Latest Commit Message

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  write-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create directory and get latest commit
        id: get_commit
        run: |
          mkdir -p workflow-outputs/commit-to-main
          git log -1 --pretty=%B > workflow-outputs/commit-to-main/latest-commit.txt
          if ! git diff --exit-code workflow-outputs/commit-to-main/latest-commit.txt; then
            echo "::notice file=workflow-outputs/commit-to-main/latest-commit.txt::File content did not change. Skipping commit."
            echo "changes_made=false" >> $GITHUB_OUTPUT
          else
            echo "changes_made=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit file
        if: steps.get_commit.outputs.changes_made == 'true'
        run: |
          git add workflow-outputs/commit-to-main/latest-commit.txt
          git commit -m "chore: Update latest commit message record"

      - name: Push changes to main
        if: success() && steps.get_commit.outputs.changes_made == 'true'
        run: git push origin main